sonar.organization=yomi-balo
sonar.projectKey=yomi-balo_balo-app

sonar.sources=apps/web/src,apps/api/src,packages/db/src,packages/shared/src
sonar.tests=apps/web/src,apps/api/src,packages/db/src,packages/shared/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/drizzle/**,**/coverage/**

sonar.cpd.exclusions=packages/db/src/schema/**

sonar.coverage.exclusions=packages/db/src/client.ts,packages/db/src/schema/helpers.ts,packages/db/src/test/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.javascript.lcov.reportPaths=coverage/lcov.info
