export { initAnalytics, analytics } from './client';
export { track } from './track';
export type { AllEvents, EventName } from '../types';

// Re-export all event constants and types for consumer convenience
export {
  AUTH_EVENTS,
  ONBOARDING_EVENTS,
  EXPERT_EVENTS,
  EXPERT_SETUP_EVENTS,
  EXPERT_RATE_EVENTS,
  EXPERT_PAYOUT_EVENTS,
  AVATAR_EVENTS,
  PHONE_EVENTS,
  CALENDAR_EVENTS,
  SEARCH_EVENTS,
  EXPERT_PROFILE_EVENTS,
  PROJECT_EVENTS,
  CONVERSATION_EVENTS,
  PROJECTS_INBOX_EVENTS,
  BILLING_EVENTS,
  ADMIN_ENGAGEMENTS_EVENTS,
  DOMAIN_JOIN_EVENTS,
} from '../events';

export type {
  AuthEventMap,
  AuthMethod,
  OnboardingEventMap,
  OnboardingStepName,
  ExpertEventMap,
  ExpertStepName,
  ExpertSetupEventMap,
  ExpertRateEventMap,
  ExpertPayoutEventMap,
  AvatarEventMap,
  PhoneEventMap,
  CalendarEventMap,
  SearchEventMap,
  ExpertProfileEventMap,
  ExpertProfileSection,
  ExpertProfileCta,
  ProfileViewport,
  ProjectEventMap,
  ProjectEntryMethod,
  ProjectStep,
  ConversationEventMap,
  ConversationLens,
  ConversationThreadSelectMethod,
  ConversationFilesSurface,
  ConversationCallSurface,
  ConversationProposalSurface,
  ProjectsInboxEventMap,
  ProjectsInboxLens,
  ProjectsInboxFilter,
  BillingEventMap,
  AdminEngagementsEventMap,
  AdminEngagementsFilter,
  DomainJoinEventMap,
} from '../events';
