export interface Country {
  code: string;
  name: string;
  flag: string;
  currency: string;
}

/** ISO codes for priority countries shown at top of selector */
export const PRIORITY_COUNTRY_CODES = ['AU', 'NZ', 'US', 'GB', 'CA', 'SG'] as const;

/**
 * Airwallex-supported countries with flag emojis and default currencies.
 * Sorted alphabetically by name. Priority countries are also included in the full list.
 */
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}', currency: 'AFN' },
  { code: 'AL', name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}', currency: 'ALL' },
  { code: 'DZ', name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}', currency: 'DZD' },
  { code: 'AD', name: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}', currency: 'EUR' },
  { code: 'AO', name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}', currency: 'AOA' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '\u{1F1E6}\u{1F1EC}', currency: 'XCD' },
  { code: 'AR', name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}', currency: 'ARS' },
  { code: 'AM', name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}', currency: 'AMD' },
  { code: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', currency: 'AUD' },
  { code: 'AT', name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}', currency: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}', currency: 'AZN' },
  { code: 'BS', name: 'Bahamas', flag: '\u{1F1E7}\u{1F1F8}', currency: 'BSD' },
  { code: 'BH', name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}', currency: 'BHD' },
  { code: 'BD', name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}', currency: 'BDT' },
  { code: 'BB', name: 'Barbados', flag: '\u{1F1E7}\u{1F1E7}', currency: 'BBD' },
  { code: 'BY', name: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}', currency: 'BYN' },
  { code: 'BE', name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}', currency: 'EUR' },
  { code: 'BZ', name: 'Belize', flag: '\u{1F1E7}\u{1F1FF}', currency: 'BZD' },
  { code: 'BJ', name: 'Benin', flag: '\u{1F1E7}\u{1F1EF}', currency: 'XOF' },
  { code: 'BT', name: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}', currency: 'BTN' },
  { code: 'BO', name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}', currency: 'BOB' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}', currency: 'BAM' },
  { code: 'BW', name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}', currency: 'BWP' },
  { code: 'BR', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}', currency: 'BRL' },
  { code: 'BN', name: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}', currency: 'BND' },
  { code: 'BG', name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}', currency: 'BGN' },
  { code: 'BF', name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}', currency: 'XOF' },
  { code: 'BI', name: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}', currency: 'BIF' },
  { code: 'KH', name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}', currency: 'KHR' },
  { code: 'CM', name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}', currency: 'XAF' },
  { code: 'CA', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}', currency: 'CAD' },
  { code: 'CV', name: 'Cape Verde', flag: '\u{1F1E8}\u{1F1FB}', currency: 'CVE' },
  { code: 'CF', name: 'Central African Republic', flag: '\u{1F1E8}\u{1F1EB}', currency: 'XAF' },
  { code: 'TD', name: 'Chad', flag: '\u{1F1F9}\u{1F1E9}', currency: 'XAF' },
  { code: 'CL', name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}', currency: 'CLP' },
  { code: 'CN', name: 'China', flag: '\u{1F1E8}\u{1F1F3}', currency: 'CNY' },
  { code: 'CO', name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}', currency: 'COP' },
  { code: 'KM', name: 'Comoros', flag: '\u{1F1F0}\u{1F1F2}', currency: 'KMF' },
  { code: 'CG', name: 'Congo', flag: '\u{1F1E8}\u{1F1EC}', currency: 'XAF' },
  { code: 'CR', name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}', currency: 'CRC' },
  { code: 'HR', name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}', currency: 'EUR' },
  { code: 'CY', name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}', currency: 'EUR' },
  { code: 'CZ', name: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}', currency: 'CZK' },
  { code: 'DK', name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}', currency: 'DKK' },
  { code: 'DJ', name: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}', currency: 'DJF' },
  { code: 'DM', name: 'Dominica', flag: '\u{1F1E9}\u{1F1F2}', currency: 'XCD' },
  { code: 'DO', name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}', currency: 'DOP' },
  { code: 'EC', name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}', currency: 'USD' },
  { code: 'EG', name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}', currency: 'EGP' },
  { code: 'SV', name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}', currency: 'USD' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '\u{1F1EC}\u{1F1F6}', currency: 'XAF' },
  { code: 'ER', name: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}', currency: 'ERN' },
  { code: 'EE', name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}', currency: 'EUR' },
  { code: 'SZ', name: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}', currency: 'SZL' },
  { code: 'ET', name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}', currency: 'ETB' },
  { code: 'FJ', name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}', currency: 'FJD' },
  { code: 'FI', name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}', currency: 'EUR' },
  { code: 'FR', name: 'France', flag: '\u{1F1EB}\u{1F1F7}', currency: 'EUR' },
  { code: 'GA', name: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}', currency: 'XAF' },
  { code: 'GM', name: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}', currency: 'GMD' },
  { code: 'GE', name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}', currency: 'GEL' },
  { code: 'DE', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}', currency: 'EUR' },
  { code: 'GH', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}', currency: 'GHS' },
  { code: 'GR', name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}', currency: 'EUR' },
  { code: 'GD', name: 'Grenada', flag: '\u{1F1EC}\u{1F1E9}', currency: 'XCD' },
  { code: 'GT', name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}', currency: 'GTQ' },
  { code: 'GN', name: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}', currency: 'GNF' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '\u{1F1EC}\u{1F1FC}', currency: 'XOF' },
  { code: 'GY', name: 'Guyana', flag: '\u{1F1EC}\u{1F1FE}', currency: 'GYD' },
  { code: 'HT', name: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}', currency: 'HTG' },
  { code: 'HN', name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}', currency: 'HNL' },
  { code: 'HK', name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HKD' },
  { code: 'HU', name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}', currency: 'ISK' },
  { code: 'IN', name: 'India', flag: '\u{1F1EE}\u{1F1F3}', currency: 'INR' },
  { code: 'ID', name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}', currency: 'IDR' },
  { code: 'IQ', name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}', currency: 'IQD' },
  { code: 'IE', name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}', currency: 'EUR' },
  { code: 'IL', name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}', currency: 'ILS' },
  { code: 'IT', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}', currency: 'EUR' },
  { code: 'CI', name: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}', currency: 'XOF' },
  { code: 'JM', name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}', currency: 'JMD' },
  { code: 'JP', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}', currency: 'JPY' },
  { code: 'JO', name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}', currency: 'JOD' },
  { code: 'KZ', name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}', currency: 'KZT' },
  { code: 'KE', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}', currency: 'KES' },
  { code: 'KI', name: 'Kiribati', flag: '\u{1F1F0}\u{1F1EE}', currency: 'AUD' },
  { code: 'KW', name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}', currency: 'KWD' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}', currency: 'KGS' },
  { code: 'LA', name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}', currency: 'LAK' },
  { code: 'LV', name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}', currency: 'EUR' },
  { code: 'LB', name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}', currency: 'LBP' },
  { code: 'LS', name: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}', currency: 'LSL' },
  { code: 'LR', name: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}', currency: 'LRD' },
  { code: 'LI', name: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}', currency: 'CHF' },
  { code: 'LT', name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}', currency: 'EUR' },
  { code: 'MO', name: 'Macau', flag: '\u{1F1F2}\u{1F1F4}', currency: 'MOP' },
  { code: 'MG', name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}', currency: 'MGA' },
  { code: 'MW', name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}', currency: 'MWK' },
  { code: 'MY', name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}', currency: 'MYR' },
  { code: 'MV', name: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}', currency: 'MVR' },
  { code: 'ML', name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}', currency: 'XOF' },
  { code: 'MT', name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}', currency: 'EUR' },
  { code: 'MH', name: 'Marshall Islands', flag: '\u{1F1F2}\u{1F1ED}', currency: 'USD' },
  { code: 'MR', name: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}', currency: 'MRU' },
  { code: 'MU', name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}', currency: 'MUR' },
  { code: 'MX', name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}', currency: 'MXN' },
  { code: 'FM', name: 'Micronesia', flag: '\u{1F1EB}\u{1F1F2}', currency: 'USD' },
  { code: 'MD', name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}', currency: 'MDL' },
  { code: 'MC', name: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}', currency: 'EUR' },
  { code: 'MN', name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}', currency: 'MNT' },
  { code: 'ME', name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}', currency: 'EUR' },
  { code: 'MA', name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}', currency: 'MAD' },
  { code: 'MZ', name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}', currency: 'MZN' },
  { code: 'MM', name: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}', currency: 'MMK' },
  { code: 'NA', name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}', currency: 'NAD' },
  { code: 'NR', name: 'Nauru', flag: '\u{1F1F3}\u{1F1F7}', currency: 'AUD' },
  { code: 'NP', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}', currency: 'NPR' },
  { code: 'NL', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}', currency: 'EUR' },
  { code: 'NZ', name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}', currency: 'NZD' },
  { code: 'NI', name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}', currency: 'NIO' },
  { code: 'NE', name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}', currency: 'XOF' },
  { code: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}', currency: 'NGN' },
  { code: 'MK', name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}', currency: 'MKD' },
  { code: 'NO', name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}', currency: 'NOK' },
  { code: 'OM', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}', currency: 'OMR' },
  { code: 'PK', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}', currency: 'PKR' },
  { code: 'PW', name: 'Palau', flag: '\u{1F1F5}\u{1F1FC}', currency: 'USD' },
  { code: 'PA', name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}', currency: 'PAB' },
  { code: 'PG', name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}', currency: 'PGK' },
  { code: 'PY', name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}', currency: 'PYG' },
  { code: 'PE', name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}', currency: 'PEN' },
  { code: 'PH', name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}', currency: 'PHP' },
  { code: 'PL', name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}', currency: 'EUR' },
  { code: 'QA', name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}', currency: 'QAR' },
  { code: 'RO', name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}', currency: 'RON' },
  { code: 'RW', name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}', currency: 'RWF' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '\u{1F1F0}\u{1F1F3}', currency: 'XCD' },
  { code: 'LC', name: 'Saint Lucia', flag: '\u{1F1F1}\u{1F1E8}', currency: 'XCD' },
  { code: 'VC', name: 'Saint Vincent', flag: '\u{1F1FB}\u{1F1E8}', currency: 'XCD' },
  { code: 'WS', name: 'Samoa', flag: '\u{1F1FC}\u{1F1F8}', currency: 'WST' },
  { code: 'SM', name: 'San Marino', flag: '\u{1F1F8}\u{1F1F2}', currency: 'EUR' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '\u{1F1F8}\u{1F1F9}', currency: 'STN' },
  { code: 'SA', name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}', currency: 'SAR' },
  { code: 'SN', name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}', currency: 'XOF' },
  { code: 'RS', name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}', currency: 'RSD' },
  { code: 'SC', name: 'Seychelles', flag: '\u{1F1F8}\u{1F1E8}', currency: 'SCR' },
  { code: 'SL', name: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}', currency: 'SLE' },
  { code: 'SG', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}', currency: 'SGD' },
  { code: 'SK', name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}', currency: 'EUR' },
  { code: 'SB', name: 'Solomon Islands', flag: '\u{1F1F8}\u{1F1E7}', currency: 'SBD' },
  { code: 'SO', name: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}', currency: 'SOS' },
  { code: 'ZA', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}', currency: 'ZAR' },
  { code: 'KR', name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}', currency: 'KRW' },
  { code: 'ES', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}', currency: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}', currency: 'LKR' },
  { code: 'SR', name: 'Suriname', flag: '\u{1F1F8}\u{1F1F7}', currency: 'SRD' },
  { code: 'SE', name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF' },
  { code: 'TW', name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}', currency: 'TWD' },
  { code: 'TJ', name: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}', currency: 'TJS' },
  { code: 'TZ', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}', currency: 'TZS' },
  { code: 'TH', name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}', currency: 'THB' },
  { code: 'TL', name: 'Timor-Leste', flag: '\u{1F1F9}\u{1F1F1}', currency: 'USD' },
  { code: 'TG', name: 'Togo', flag: '\u{1F1F9}\u{1F1EC}', currency: 'XOF' },
  { code: 'TO', name: 'Tonga', flag: '\u{1F1F9}\u{1F1F4}', currency: 'TOP' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}', currency: 'TTD' },
  { code: 'TN', name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}', currency: 'TND' },
  { code: 'TR', name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}', currency: 'TRY' },
  { code: 'TM', name: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}', currency: 'TMT' },
  { code: 'TV', name: 'Tuvalu', flag: '\u{1F1F9}\u{1F1FB}', currency: 'AUD' },
  { code: 'UG', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}', currency: 'UGX' },
  { code: 'UA', name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}', currency: 'UAH' },
  { code: 'AE', name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}', currency: 'GBP' },
  { code: 'US', name: 'United States', flag: '\u{1F1FA}\u{1F1F8}', currency: 'USD' },
  { code: 'UY', name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}', currency: 'UYU' },
  { code: 'UZ', name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}', currency: 'UZS' },
  { code: 'VU', name: 'Vanuatu', flag: '\u{1F1FB}\u{1F1FA}', currency: 'VUV' },
  { code: 'VN', name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}', currency: 'VND' },
  { code: 'ZM', name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}', currency: 'ZMW' },
  { code: 'ZW', name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}', currency: 'ZWL' },
];

/** Pre-computed map for O(1) lookups */
const COUNTRY_MAP = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRY_MAP.get(code);
}

export function getPriorityCountries(): Country[] {
  return PRIORITY_COUNTRY_CODES.map((code) => COUNTRY_MAP.get(code)).filter(
    (c): c is Country => !!c
  );
}
