/**
 * BAL-275 §8 — generated, deterministic dev fixtures for the fast-forward's synthetic steps.
 *
 * PURE: no I/O, no clock beyond what callers pass, no `server-only`. Two of the seven targets
 * (`eoi_submitted`, `proposal_submitted`) and the `closed` action need SOME content the real
 * handler will persist — a message, a proposal, a note — because none of those handlers accepts
 * an empty one. This module is the SINGLE place that content is defined, and it is minimal but
 * COHERENT (D7): every real validation the content would hit on a genuine submission still has
 * to pass, never bypassed or re-implemented. `fast-forward-fixtures.test.ts` proves that against
 * the REAL `validateProposalReadiness` / `installmentsSumTo100` / `sanitizeProjectHtml` /
 * `proposalDraftBaseFields` — never a reimplementation of any of them.
 */

import type { SaveProposalDraftInput } from '@/app/(dashboard)/projects/[requestId]/_actions/_shared/save-proposal-draft-core';

/**
 * §8.1 — the EOI message. Gender-neutral, ≥1 char, ≤20 000 bytes (the core's own byte guard),
 * and survives `sanitizeProjectHtml` (a bare `<p>` with text) and therefore `isDescriptionEmpty`.
 */
export const FAST_FORWARD_EOI_MESSAGE =
  '<p>Generated by the BAL-275 dev fast-forward so this request could reach a later state for ' +
  'testing. It carries no commercial meaning and does not represent a real expression of interest.</p>';

/**
 * §8.2 — the smallest COHERENT proposal draft: one milestone, one installment, fixed price.
 * Driven through the REAL chain (`createDraft` → `updateDraft` → `setForProposal` ×2 →
 * `promoteToSubmit`) by the orchestrator — this function only builds the input.
 *
 * `currency` is deliberately OMITTED — the `proposals` schema default (`'aud'`,
 * `packages/db/src/schema/request-origination.ts:297`) applies, exactly as when the real
 * composer omits it. Do not hardcode a currency here (§17 open question — confirmed: the schema
 * carries a `.default('aud')`, so `createDraft` receiving `currency: undefined` is the same
 * "let the schema decide" path a genuine partial-draft autosave takes).
 */
export function fastForwardProposalDraft(
  requestId: string,
  relationshipId: string
): SaveProposalDraftInput {
  return {
    requestId,
    relationshipId,
    overview:
      '<p>Generated by the BAL-275 dev fast-forward. One milestone, one installment, fixed price — ' +
      'the smallest shape that satisfies the real coherence rules. Not a real proposal.</p>',
    pricingMethod: 'fixed',
    priceCents: 1_200_000, // A$12,000.00 — well under MAX_CENTS
    timeframeWeeks: 4,
    milestones: [
      {
        title: 'Discovery and delivery',
        descriptionHtml: null,
        acceptanceCriteria: null,
        valueCents: 1_200_000,
        estimatedMinutes: null, // force-nulled for `fixed` by the repository anyway
      },
    ],
    installments: [{ label: 'On completion', pct: 100 }],
  };
}

/**
 * §8.3 — the close note the Balo-arm close action requires. ≥8 chars (the action's own Zod
 * `.min(8)`), ≤2000, staff-only — never lens-serialised to a client or expert (D11).
 */
export const FAST_FORWARD_CLOSE_NOTE =
  'Closed by the BAL-275 dev fast-forward to produce a closed-request fixture. Not a real decision.';
