-- BAL-561 / D1 — "at most one LIVE account per email, case-insensitively", by construction: a
-- partial unique index on `lower(email)` backing the Staff access email lookup
-- (`usersRepository.findStaffCandidateByEmail`, which matches `lower(email) = lower($1)` with
-- `LIMIT 1` and names this index as its guarantee).
--
-- HEADER-ONLY HAND EDIT after `drizzle-kit generate`: the statement below is exactly what was
-- generated, unmodified, and a second `drizzle-kit generate` reports no schema changes (the
-- snapshot round-trips the expression index). (Precedent for an explanatory header on generated
-- SQL: 0095_bal489_guest_conversion_linkage.sql.)
--
-- ── ⚠ THIS BUILD FAILS IF LIVE CASE-VARIANT DUPLICATES ALREADY EXIST — AND CI CANNOT TELL YOU ──
-- The integration harness migrates an EMPTY database, so CI passing on this migration proves
-- nothing about a populated table. `users_email_unique` (0042) is CASE-SENSITIVE and emails are
-- stored exactly as WorkOS returns them, so two live rows differing only in case are legal today
-- and would make this `CREATE UNIQUE INDEX` fail 23505, aborting the deploy's migration run. The
-- orchestrator runs a count-only check against production BEFORE merge (no emails returned):
--   SELECT count(*) FROM (SELECT 1 FROM users WHERE deleted_at IS NULL
--                         GROUP BY lower(email) HAVING count(*) > 1) d;
-- A non-zero count means stop and rule on the duplicates first.
--
-- ── LOCKING ──────────────────────────────────────────────────────────────────────────────────
-- A plain (non-CONCURRENT) build, because drizzle-kit migrations run inside a transaction and
-- `CREATE INDEX CONCURRENTLY` cannot. It holds a SHARE lock on `users` for the build — reads
-- proceed, writes (sign-up, profile edits, `last_active_at` touches) wait — over a small table on
-- a pre-launch product.
--
-- ── `users_email_unique` IS KEPT (D1) ───────────────────────────────────────────────────────────
-- Nothing is gained by dropping it, and no upsert arbiter targets either index today (no
-- `onConflict*` names `users.email`; `seed.ts` uses a target-less `onConflictDoNothing`), and no
-- insert path maps a 23505 by constraint name, so which of the two an exact duplicate reports is
-- not a contract anything relies on.
--
-- ── WHAT CHANGES FOR SIGN-IN / SIGN-UP ──────────────────────────────────────────────────────────
-- A new 23505 surface on every `users` INSERT path. A WorkOS identity whose email differs only in
-- case from a live account under another `workos_id` now fails closed through each path's
-- existing generic catch (logged, nothing partially written) instead of silently creating a
-- second live account. Enumerated in the BAL-561 plan §3; ruled acceptable in P7.
CREATE UNIQUE INDEX "users_email_lower_unique" ON "users" USING btree (lower("email")) WHERE "users"."deleted_at" IS NULL;