import { pgTable, uuid, text, jsonb, index, timestamp, bigint } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { users } from './users';

/**
 * audit_events (BAL-344) — a generic, reusable, append-only audit log for the
 * whole platform. Introduced for domain auto-capture but deliberately domain-
 * agnostic: any feature can record an immutable "who did what to which entity"
 * row, participating in the same transaction as the change it records.
 *
 * `actorUserId` NULLABLE (system/automated events may have no human actor);
 * RESTRICT to preserve attribution. `action` / `entityType` are TEXT not enums —
 * the audit vocabulary is open-ended and grows without a migration per event.
 *
 * IMMUTABILITY: this table is genuinely append-only. Rows are only ever inserted —
 * never updated (there is no `updated_at` and no `$onUpdate` hook) and never
 * soft-deleted (there is no `deleted_at`); it carries a single `created_at`. This
 * is a deliberate, documented exception to the CLAUDE.md "every table gets
 * created_at/updated_at/deleted_at" convention, justified because an audit ledger
 * must be immutable — mutating or deleting audit rows would defeat the purpose of
 * the log.
 *
 * ⚠ APPEND-ONLY HERE MEANS **COLUMNS ONLY**: no `updated_at`, no `deleted_at`. It is NOT a
 * DB-level insert-only guard, and a trigger/rule enforcing one would break two deliberate,
 * documented paths: `apps/api/src/services/seed/truncate.ts:227` DELETEs engagement-scoped audit
 * rows (its own header calls this the one hygiene exception, and it uses DELETE rather than
 * TRUNCATE precisely so the identity sequence is never reset), and
 * `audit-events.integration.test.ts` UPDATEs `created_at` to fabricate distinct timestamps the
 * transaction-scoped default cannot produce. Do not add such a guard.
 */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * BAL-426 — the monotonic append-order tiebreaker: a Postgres IDENTITY sequence, NOT the
     * random-uuid PK. `created_at` is `defaultNow()` = `transaction_timestamp()`, so EVERY row
     * written inside one `db.transaction` carries an IDENTICAL instant — and ADR-1030 makes
     * several audit rows per transaction the DESIGNED shape, not an edge case. `seq` is what
     * makes those rows orderable at all.
     *
     * ⚠⚠ THE CONTRACT IS `created_at` THEN `seq`, BOTH COLUMNS IN THE SAME DIRECTION.
     * Ascending readers use `asc(createdAt), asc(seq)`; descending readers use
     * `desc(createdAt), desc(seq)`. It is NOT a fixed `(created_at ASC, seq ASC)` pair: pasting
     * the ascending form into a `DESC … LIMIT 1` reader (`findLatestByEntityAndAction`) returns
     * the EARLIEST row of a same-transaction tie and silently inverts that function. And NEVER
     * tiebreak on `id` — it is `defaultRandom()`, so `(created_at, id)` is a coin flip per run,
     * which is the exact defect this column exists to remove.
     * `packages/db/src/invariants/audit-trail-ordering.test.ts` holds all three halves of that
     * mechanically, on every unit run.
     *
     * ⚠ WHY THIS DIVERGES FROM `credit_ledger.seq`, WHICH ORDERS BY `seq` ALONE. Do not "align"
     * them in either direction — they are different orders on purpose:
     *   · `credit_ledger` appends for one wallet are serialised by a per-wallet
     *     `pg_advisory_xact_lock` (`_shared/wallet-lock.ts`, held to COMMIT), so for a wallet
     *     `seq` order IS commit order and the running `balance_after_minor` is DEFINED against
     *     append order. `seq` alone is correct AND necessary there.
     *   · `audit_events` has NO such serialisation point — every feature writes it, for every
     *     entity type, under whatever (or no) lock. A sequence orders INSERTS, not COMMITS, so
     *     `seq` alone here would advertise a global chronology this table cannot deliver, and
     *     would let two concurrently-open transactions INTERLEAVE (A₁ B₂ B₃ A₄), splitting one
     *     atomic change across another's rows. Leading with `created_at` keeps each
     *     transaction's rows CONTIGUOUS — which is the meaning `created_at` carries here,
     *     "these rows were one change" — and confines `seq` to breaking ties WITHIN one
     *     transaction, the only claim this table can honestly make.
     *
     * GAPS ARE EXPECTED AND CORRECT: sequences are non-transactional, so a rolled-back
     * transaction still consumes values. `seq` is an ORDERING KEY, never a count — nothing may
     * derive "how many events" from `max(seq)`.
     *
     * GENERATED ALWAYS ⇒ never writer-set. The sole insert path in the repo,
     * `auditEventsRepository.record`, names five columns and never this one. A future backfill
     * or import that must set `seq` explicitly would need `INSERT … OVERRIDING SYSTEM VALUE`
     * (or a one-off `ALTER COLUMN seq SET GENERATED BY DEFAULT`); no path needs that today.
     */
    seq: bigint('seq', { mode: 'number' }).generatedAlwaysAsIdentity(),

    // Who performed the action. NULLABLE (system/automated events may have no
    // human actor); restrict to preserve attribution.
    actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'restrict' }),

    // Dot-namespaced event type, e.g. 'party_domain.captured'. TEXT not enum —
    // the audit vocabulary is open-ended and grows without a migration per event.
    action: text('action').notNull(),

    // The affected entity. entityType groups by domain ('party_domain'); entityId
    // is that row's uuid (all Balo PKs are uuid).
    entityType: text('entity_type').notNull(),
    entityId: uuid('entity_id').notNull(),

    // Arbitrary structured context. Typed per drizzle-schema JSONB rule.
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),

    // Append-only: a single created_at, no updated_at / no deleted_at (see the
    // IMMUTABILITY note above).
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    // "History of one entity" — the primary read path.
    index('audit_events_entity_idx').on(t.entityType, t.entityId),
    index('audit_events_actor_idx').on(t.actorUserId),
    index('audit_events_action_idx').on(t.action),
    index('audit_events_created_at_idx').on(t.createdAt),
  ]
);

// ── Relations ──────────────────────────────────────────────────────────

export const auditEventsRelations = relations(auditEvents, ({ one }) => ({
  actor: one(users, { fields: [auditEvents.actorUserId], references: [users.id] }),
}));

// ── Type exports ───────────────────────────────────────────────────────

export type AuditEvent = typeof auditEvents.$inferSelect;
export type NewAuditEvent = typeof auditEvents.$inferInsert;
